# Лидеры Цифровой Трансформации 2021, трек 6, команда R2D2

## Код выгрузки данных с API data.mos , импорта файлов с расширениями .csv .xls .xlsx и преобразования этих файлов



Выполнила Шушпанова Мария.

В связи с тем, что API data.mos перестал работать и сайт стал выдавать оишбку, было принято решение импортировать исходные данные с портала data.mos и работать с ними локально. Скачать и посмотреть исходные данные вы можете по этой ссылке: https://disk.yandex.ru/d/i5XbZWB-uJvFFg

Загрузка библиотек

In [1]:
import pandas as pd
import numpy as np
from simpledbf import Dbf5
import random
import json
from tqdm import tqdm

PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.

Для работы с рекомендательной системой должны использоваться данные, полученные из открытых источников (API). Так как на момент решения данной задачи были сложности с получением даннных с API data.mos (ошибка на сайте), решено было использовать файлы с расширениями .csv и .xlsx , полученные с сайта data.mos посредством импорта файлов. 

Пример кода для выгрузки с API data.mos датасета, поддерживающий метод features

In [ ]:
''''key = '?api_key=<ваш ключ>'
url = 'https://apidata.mos.ru/v1/datasets/<номер датасета>/features' 

name_dataset_df = []
try:
    response = requests.get(url+key)
    json_response = response.json()

    name_dataset_df += json_response['features']
except Exception as ex:
    print(ex)'''

Пример кода для выгрузки с API data.mos датасета, поддерживающий метод rows

In [ ]:
'''key = '?api_key=<ваш ключ>''
url = 'https://apidata.mos.ru/v1/datasets/<номер датасета>/rows' 


name_dataset_df = []

try:
    response = requests.get(url+key)
    json_response = response.json()

    name_dataset_df += json_response
except Exception as ex:
    print(ex)'''

Выгрузки, изменения названий колонок, заполнение пропусков и изменение типов данных у датасетов, предоставленных организаторами хакатона

In [2]:
Location_July = pd.read_csv('01_Location_July.csv')
Location_July = Location_July.rename({'zid' : 'adm_zid'}, axis = 1)

CLocation_July = pd.read_csv('01_CLocation_July.csv')
CLocation_July = CLocation_July.rename({'zid' : 'cell_zid'}, axis = 1)

Matrix_Home_Work_July = pd.read_csv('04_Matrix_Home_Work_July.csv')
Matrix_Home_Work_July = Matrix_Home_Work_July.rename({'home_zid' : 'home_adm_zid', 'work_zid' : 'work_adm_zid'}, axis = 1)

CMatrix_Home_Work_July = pd.read_csv('04_CMatrix_Home_Work_July.csv')
CMatrix_Home_Work_July = CMatrix_Home_Work_July.rename({'home_zid' : 'home_cell_zid', 'work_zid' : 'work_cell_zid'}, axis = 1)

display(Location_July, CLocation_July, Matrix_Home_Work_July, CMatrix_Home_Work_July)

,adm_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,1,31723,11029,23944,1411
1,2,64780,15890,40845,3536
2,3,69098,39701,63486,4161
3,4,28261,11886,23643,1234
4,5,50667,42403,61042,2543
...,...,...,...,...,...
141,250,36848,7849,23733,1886
142,264,26256,6393,17502,1327
143,271,56176,12938,36688,3013
144,272,23948,16135,25070,998
145,276,34128,9745,23079,1936

,cell_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,32909,4,0,0,0
1,32910,25,8,26,0
2,33261,2,0,2,0
3,33262,13,2,11,0
4,33263,10,0,3,0
...,...,...,...,...,...
10235,138913,77,455,495,1
10236,138914,165,796,884,8
10237,138915,587,1341,1661,19
10238,138916,1206,1669,2177,47
10239,139343,75,233,269,5

       home_adm_zid  work_adm_zid  customers_cnt
0                -2             1           2434
1                -2             2           3858
2                -2             3           6667
3                -2             4           2211
4                -2             5           8622
...             ...           ...            ...
20603           276           250             15
20604           276           264            251
20605           276           271            456
20606           276           272             27
20607           276           276           2888

[20608 rows x 3 columns]

        home_cell_zid  work_cell_zid  customers_cnt
0                  -2          33620              2
1                  -2          33622              2
2                  -2          33623              3
3                  -2          33624              3
4                  -2          33967              5
...               ...            ...            ...
724438         138916         138912              1
724439         138916         138916             25
724440         139343             -2              8
724441         139343             -1             64
724442         139343         138915              3

[724443 rows x 3 columns]

In [3]:
Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК = pd.read_excel('Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК.xlsx', engine='openpyxl')
display(Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК)

,cell_zid,area_peresechenia_s_admzone_kv.km,adm_zid,adm_name,okrug_name,sub_ter
0,32909,0.407116,216,Роговское,Троицкий административный округ,Новая Москва
1,32910,1.003458,216,Роговское,Троицкий административный округ,Новая Москва
2,33261,0.233312,216,Роговское,Троицкий административный округ,Новая Москва
3,33262,1.868032,216,Роговское,Троицкий административный округ,Новая Москва
4,33263,2.500630,216,Роговское,Троицкий административный округ,Новая Москва
...,...,...,...,...,...,...
13227,138914,0.585913,1,Силино,Зеленоградский административный округ,Старая Москва
13228,138915,2.342729,6,Матушкино,Зеленоградский административный округ,Старая Москва
13229,138915,0.157932,1,Силино,Зеленоградский административный округ,Старая Москва
13230,138916,2.315494,6,Матушкино,Зеленоградский административный округ,Старая Москва
13231,139343,1.937024,1,Силино,Зеленоградский административный округ,Старая Москва

In [4]:
dbf = Dbf5('admzones2021.dbf', codec='utf-8')
dbf.to_csv('admzones.csv')
admzones2021 = pd.read_csv('admzones.csv')
admzones2021['okrug_name'] = admzones2021['okrug_name'].fillna('нет информации')
admzones2021['okrug_id'] = admzones2021['okrug_id'].fillna(0)
admzones2021 = admzones2021.drop_duplicates()
admzones2021 = admzones2021.drop(index=[206]) #использовать по необходимости
admzones2021['adm_zid'] = admzones2021['adm_zid'].astype('int64')
display(admzones2021)

,adm_zid,adm_name,okrug_name,sub_ter,okrug_id,area
0,519,Коломна,нет информации,Московская область,0,1728866475.30917
1,507,Дзержинский,нет информации,Московская область,0,15664300.4293
2,109,Перово,Восточный административный округ,Старая Москва,561,9829907.8448
3,533,Мытищи,нет информации,Московская область,0,431245916.40407
4,66,Тверской,Центральный административный округ,Старая Москва,569,7322587.74128
...,...,...,...,...,...,...
201,515,Звездный городок,нет информации,Московская область,0,3179076.93197
202,535,Ногинск (Богородский),нет информации,Московская область,0,810180991.91751
203,560,Электросталь,нет информации,Московская область,0,135398473.53206
204,526,Лосино-Петровский,нет информации,Московская область,0,91289704.85397
205,558,Щелково,нет информации,Московская область,0,622902867.66227

In [ ]:
with open('fishnet2021.json', 'r', encoding='utf-8') as f:
    fishnet2021_geo = json.load(f)
    fishnet2021_geo_df = pd.DataFrame(fishnet2021_geo)

fishnet2021_geo_df_2  = fishnet2021_geo_df['geometries']

coord_df = pd.DataFrame()
for i in tqdm(range(len(fishnet2021_geo_df_2))):
    element = pd.DataFrame(fishnet2021_geo_df_2[i])
    coord_df = pd.concat([coord_df, element])
    i +=1
    
coordinates_df = coord_df
coordinates_df = coordinates_df.reset_index(drop=True)

In [5]:
dbf = Dbf5('fishnet2021.dbf', codec='utf-8')
dbf.to_csv('fishnet2021.csv')
fishnet2021_dataset = pd.read_csv('fishnet2021.csv')
fishnet2021_dataset = fishnet2021_dataset.drop_duplicates()
fishnet2021_dataset = fishnet2021_dataset.drop(index=[189892]) #использовать по необходимости

display(fishnet2021_dataset)

       cell_zid
0             0
1             1
2             2
3             3
4             4
...         ...
189887   190237
189888   190238
189889   190239
189890   190240
189891   190241

[189892 rows x 1 columns]

Создание справочника соотношения ячеек cell_zid и их географических координат

In [ ]:
cell_zid_geo = pd.merge(fishnet2021_dataset, coordinates_df, left_index=True, right_index=True)
cell_zid_geo = cell_zid_geo.drop('type', axis=1)

Создание справочника соотношения cell_zid к конкретному району для понимания, откуда и куда перемещаются люди.

In [6]:
CLocation_July_zid = pd.merge(CLocation_July, Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК, on='cell_zid', how='left')
display(CLocation_July_zid)

,cell_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move,area_peresechenia_s_admzone_kv.km,adm_zid,adm_name,okrug_name,sub_ter
0,32909,4,0,0,0,0.407116,216,Роговское,Троицкий административный округ,Новая Москва
1,32910,25,8,26,0,1.003458,216,Роговское,Троицкий административный округ,Новая Москва
2,33261,2,0,2,0,0.233312,216,Роговское,Троицкий административный округ,Новая Москва
3,33262,13,2,11,0,1.868032,216,Роговское,Троицкий административный округ,Новая Москва
4,33263,10,0,3,0,2.500630,216,Роговское,Троицкий административный округ,Новая Москва
...,...,...,...,...,...,...,...,...,...,...
13215,138914,165,796,884,8,0.585913,1,Силино,Зеленоградский административный округ,Старая Москва
13216,138915,587,1341,1661,19,2.342729,6,Матушкино,Зеленоградский административный округ,Старая Москва
13217,138915,587,1341,1661,19,0.157932,1,Силино,Зеленоградский административный округ,Старая Москва
13218,138916,1206,1669,2177,47,2.315494,6,Матушкино,Зеленоградский административный округ,Старая Москва
13219,139343,75,233,269,5,1.937024,1,Силино,Зеленоградский административный округ,Старая Москва

In [7]:
Location_July_zid = pd.merge(Location_July, Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК, on='adm_zid', how='left')
display(Location_July_zid)

,adm_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move,cell_zid,area_peresechenia_s_admzone_kv.km,adm_name,okrug_name,sub_ter
0,1,31723,11029,23944,1411,135416,0.004153,Силино,Зеленоградский административный округ,Старая Москва
1,1,31723,11029,23944,1411,135866,0.012463,Силино,Зеленоградский административный округ,Старая Москва
2,1,31723,11029,23944,1411,135867,1.740384,Силино,Зеленоградский административный округ,Старая Москва
3,1,31723,11029,23944,1411,135868,0.749847,Силино,Зеленоградский административный округ,Старая Москва
4,1,31723,11029,23944,1411,136315,1.036443,Силино,Зеленоградский административный округ,Старая Москва
...,...,...,...,...,...,...,...,...,...,...
13227,276,34128,9745,23079,1936,78763,0.726060,Щербинка,Новомосковский административный округ,Новая Москва
13228,276,34128,9745,23079,1936,78764,1.875625,Щербинка,Новомосковский административный округ,Новая Москва
13229,276,34128,9745,23079,1936,78765,1.760400,Щербинка,Новомосковский административный округ,Новая Москва
13230,276,34128,9745,23079,1936,78766,0.535573,Щербинка,Новомосковский административный округ,Новая Москва
13231,276,34128,9745,23079,1936,78770,0.215892,Щербинка,Новомосковский административный округ,Новая Москва

Создание справочника соотношения величины территории района с его adm_zid и id округа.

In [8]:
CLocation_July_zid_areas = pd.merge(CLocation_July_zid, admzones2021[['adm_zid', 'area', 'okrug_id']], on='adm_zid', how='left')
display(CLocation_July_zid_areas)

,cell_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move,area_peresechenia_s_admzone_kv.km,adm_zid,adm_name,okrug_name,sub_ter,area,okrug_id
0,32909,4,0,0,0,0.407116,216,Роговское,Троицкий административный округ,Новая Москва,178218314.8871,572
1,32910,25,8,26,0,1.003458,216,Роговское,Троицкий административный округ,Новая Москва,178218314.8871,572
2,33261,2,0,2,0,0.233312,216,Роговское,Троицкий административный округ,Новая Москва,178218314.8871,572
3,33262,13,2,11,0,1.868032,216,Роговское,Троицкий административный округ,Новая Москва,178218314.8871,572
4,33263,10,0,3,0,2.500630,216,Роговское,Троицкий административный округ,Новая Москва,178218314.8871,572
...,...,...,...,...,...,...,...,...,...,...,...,...
13215,138914,165,796,884,8,0.585913,1,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563
13216,138915,587,1341,1661,19,2.342729,6,Матушкино,Зеленоградский административный округ,Старая Москва,5029622.92028,563
13217,138915,587,1341,1661,19,0.157932,1,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563
13218,138916,1206,1669,2177,47,2.315494,6,Матушкино,Зеленоградский административный округ,Старая Москва,5029622.92028,563
13219,139343,75,233,269,5,1.937024,1,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563

In [9]:
Location_July_zid_areas = pd.merge(Location_July_zid, admzones2021[['adm_zid', 'area', 'okrug_id']], on='adm_zid', how='left')
display(Location_July_zid_areas)

,adm_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move,cell_zid,area_peresechenia_s_admzone_kv.km,adm_name,okrug_name,sub_ter,area,okrug_id
0,1,31723,11029,23944,1411,135416,0.004153,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563
1,1,31723,11029,23944,1411,135866,0.012463,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563
2,1,31723,11029,23944,1411,135867,1.740384,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563
3,1,31723,11029,23944,1411,135868,0.749847,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563
4,1,31723,11029,23944,1411,136315,1.036443,Силино,Зеленоградский административный округ,Старая Москва,9436377.17444,563
...,...,...,...,...,...,...,...,...,...,...,...,...
13227,276,34128,9745,23079,1936,78763,0.726060,Щербинка,Новомосковский административный округ,Новая Москва,7584638.30649,571
13228,276,34128,9745,23079,1936,78764,1.875625,Щербинка,Новомосковский административный округ,Новая Москва,7584638.30649,571
13229,276,34128,9745,23079,1936,78765,1.760400,Щербинка,Новомосковский административный округ,Новая Москва,7584638.30649,571
13230,276,34128,9745,23079,1936,78766,0.535573,Щербинка,Новомосковский административный округ,Новая Москва,7584638.30649,571
13231,276,34128,9745,23079,1936,78770,0.215892,Щербинка,Новомосковский административный округ,Новая Москва,7584638.30649,571

Создание справочника предполагаемых районов (по ячейкам cell_zid), куда люди ездят на работу и где живут.

In [10]:
Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_home = Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК.copy()
Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_home = Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_home.rename({'cell_zid' : 'home_cell_zid'}, axis=1)

Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_work = Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_home.copy()
Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_work = Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_work.rename({'home_cell_zid' : 'work_cell_zid'}, axis=1)


CMatrix_Home_Work_July_adm_zid = CMatrix_Home_Work_July.merge(Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_home, on='home_cell_zid', how='left')
CMatrix_Home_Work_July_adm_zid = CMatrix_Home_Work_July_adm_zid.rename(columns={'adm_zid' : 'home_adm_zid', 'adm_name' : 'home_adm_name', 'okrug_name' : 'home_okrug_name', 'sub_ter' : 'home_sub_ter'})
CMatrix_Home_Work_July_adm_zid = CMatrix_Home_Work_July_adm_zid.rename({'work_zid' : 'work_cell_zid'}, axis=1)

CMatrix_Home_Work_July_adm_zid_work_home = CMatrix_Home_Work_July_adm_zid.merge(Справочник_соотношения_секторов_500х500м_и_адм_районов_МСК_work, on='work_cell_zid', how='left')
CMatrix_Home_Work_July_adm_zid_work_home = CMatrix_Home_Work_July_adm_zid_work_home.rename(columns={'adm_zid' : 'work_adm_zid', 'adm_name' : 'work_adm_name', 'okrug_name' : 'work_okrug_name', 'sub_ter' : 'work_sub_ter'})


display(CMatrix_Home_Work_July_adm_zid_work_home)

,home_cell_zid,work_cell_zid,customers_cnt,area_peresechenia_s_admzone_kv.km_x,home_adm_zid,home_adm_name,home_okrug_name,home_sub_ter,area_peresechenia_s_admzone_kv.km_y,work_adm_zid,work_adm_name,work_okrug_name,work_sub_ter
0,-2,33620,2,NaN,NaN,NaN,NaN,NaN,2.500637,216.0,Роговское,Троицкий административный округ,Новая Москва
1,-2,33622,2,NaN,NaN,NaN,NaN,NaN,2.500640,216.0,Роговское,Троицкий административный округ,Новая Москва
2,-2,33623,3,NaN,NaN,NaN,NaN,NaN,2.500642,216.0,Роговское,Троицкий административный округ,Новая Москва
3,-2,33624,3,NaN,NaN,NaN,NaN,NaN,2.218432,216.0,Роговское,Троицкий административный округ,Новая Москва
4,-2,33967,5,NaN,NaN,NaN,NaN,NaN,2.500629,216.0,Роговское,Троицкий административный округ,Новая Москва
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600136,138916,138916,25,2.315494,6.0,Матушкино,Зеленоградский административный округ,Старая Москва,2.315494,6.0,Матушкино,Зеленоградский административный округ,Старая Москва
1600137,139343,-2,8,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,NaN,NaN,NaN,NaN,NaN
1600138,139343,-1,64,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,NaN,NaN,NaN,NaN,NaN
1600139,139343,138915,3,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,2.342729,6.0,Матушкино,Зеленоградский административный округ,Старая Москва
1600140,139343,138915,3,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,0.157932,1.0,Силино,Зеленоградский административный округ,Старая Москва

Заполнение пропусков NaN, редактирование колонок датафрейма.

In [11]:
def groups_city(zid_first, value_first, value_second, value_third):
    if zid_first == -1:
        return value_first
    if zid_first == -2:
        return value_second
    else:
        return value_third
    
CMatrix_Home_Work_July_adm_zid_work_home['home_adm_name'] = CMatrix_Home_Work_July_adm_zid_work_home.apply(lambda x: groups_city(zid_first = x['home_cell_zid'], value_first = 'Москва', value_second = 'Московская область', value_third = x['home_adm_name']), axis = 1)
CMatrix_Home_Work_July_adm_zid_work_home['work_adm_name'] = CMatrix_Home_Work_July_adm_zid_work_home.apply(lambda x: groups_city(zid_first = x['work_cell_zid'], value_first = 'Москва', value_second = 'Московская область', value_third = x['work_adm_name']), axis = 1)

CMatrix_Home_Work_July_adm_zid_work_home['home_okrug_name'] = CMatrix_Home_Work_July_adm_zid_work_home['home_okrug_name'].fillna('нет информации')
CMatrix_Home_Work_July_adm_zid_work_home['home_sub_ter'] = CMatrix_Home_Work_July_adm_zid_work_home['home_sub_ter'].fillna('нет информации')
CMatrix_Home_Work_July_adm_zid_work_home['work_okrug_name'] = CMatrix_Home_Work_July_adm_zid_work_home['work_okrug_name'].fillna('нет информации')
CMatrix_Home_Work_July_adm_zid_work_home['work_sub_ter'] = CMatrix_Home_Work_July_adm_zid_work_home['work_sub_ter'].fillna('нет информации')
CMatrix_Home_Work_July_adm_zid_work_home['home_adm_zid'] = CMatrix_Home_Work_July_adm_zid_work_home['home_adm_zid'].fillna(0)
CMatrix_Home_Work_July_adm_zid_work_home['work_adm_zid'] = CMatrix_Home_Work_July_adm_zid_work_home['work_adm_zid'].fillna(0)
CMatrix_Home_Work_July_adm_zid_work_home['area_peresechenia_s_admzone_kv.km_y'] = CMatrix_Home_Work_July_adm_zid_work_home['area_peresechenia_s_admzone_kv.km_y'].fillna(0)
CMatrix_Home_Work_July_adm_zid_work_home['area_peresechenia_s_admzone_kv.km_x'] = CMatrix_Home_Work_July_adm_zid_work_home['area_peresechenia_s_admzone_kv.km_x'].fillna(0)


display(CMatrix_Home_Work_July_adm_zid_work_home)

,home_cell_zid,work_cell_zid,customers_cnt,area_peresechenia_s_admzone_kv.km_x,home_adm_zid,home_adm_name,home_okrug_name,home_sub_ter,area_peresechenia_s_admzone_kv.km_y,work_adm_zid,work_adm_name,work_okrug_name,work_sub_ter
0,-2,33620,2,0.000000,0.0,Московская область,нет информации,нет информации,2.500637,216.0,Роговское,Троицкий административный округ,Новая Москва
1,-2,33622,2,0.000000,0.0,Московская область,нет информации,нет информации,2.500640,216.0,Роговское,Троицкий административный округ,Новая Москва
2,-2,33623,3,0.000000,0.0,Московская область,нет информации,нет информации,2.500642,216.0,Роговское,Троицкий административный округ,Новая Москва
3,-2,33624,3,0.000000,0.0,Московская область,нет информации,нет информации,2.218432,216.0,Роговское,Троицкий административный округ,Новая Москва
4,-2,33967,5,0.000000,0.0,Московская область,нет информации,нет информации,2.500629,216.0,Роговское,Троицкий административный округ,Новая Москва
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600136,138916,138916,25,2.315494,6.0,Матушкино,Зеленоградский административный округ,Старая Москва,2.315494,6.0,Матушкино,Зеленоградский административный округ,Старая Москва
1600137,139343,-2,8,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,0.000000,0.0,Московская область,нет информации,нет информации
1600138,139343,-1,64,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,0.000000,0.0,Москва,нет информации,нет информации
1600139,139343,138915,3,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,2.342729,6.0,Матушкино,Зеленоградский административный округ,Старая Москва
1600140,139343,138915,3,1.937024,1.0,Силино,Зеленоградский административный округ,Старая Москва,0.157932,1.0,Силино,Зеленоградский административный округ,Старая Москва

Выгрузка с API data.mos  информации об образовательных учреждениях города Москвы.

In [ ]:
'''key = '?api_key=<ваш ключ>'
url = 'https://apidata.mos.ru/v1/datasets/2263/features' 

schools_df = []

try:
    response = requests.get(url+key)
    json_response = response.json()

    schools_df += json_response['features']
except Exception as ex:
    print(ex)
    
schools_dataset = pd.DataFrame(schools_df)
schools_dataset = schools_dataset["properties"].apply(pd.Series)
schools_name = schools_dataset["Attributes"].apply(pd.Series) '''

Раскрытие информации о дополнительных корпусах школ.

In [ ]:
'''schools_address = schools_name["InstitutionsAddresses"]

df_school = pd.DataFrame()
for i in range(len(schools_address)):
    element = pd.DataFrame(schools_address[i])
    df_school = pd.concat([df_school, element])
    i +=1'''

Соединение информации об адресах корпусов и главных зданий образовательных учреждений, редактирование названий колонок датафрейма.

In [ ]:
'''schools_name_2 = schools_name.copy()
schools_name_2 = schools_name_2.drop('InstitutionsAddresses', 1)
df_school_2 = df_school[['AdmArea', 'District', 'Address', 'global_id']]
schools_name_addresses = schools_name_2.merge(df_school_2, on='FullName', how='right' )
schools_name_addresses = schools_name_addresses.rename({'global_id_x' : 'global_id'}, axis = 1)
schools_name_addresses_2 = schools_name_addresses.drop(['WebSite_y', 'PublicPhone_y', 'ChiefName_y', 'global_id_y'], 1)
schools_name_addresses_2 = schools_name_addresses_2.rename(columns={'WebSite_x' : 'WebSite', 'PublicPhone_x' : 'PublicPhone', 'ChiefName_x' : 'ChiefName'})
schools_name_addresses_data_mos_wo_duplicate = schools_name_addresses_2'''

Так как сайт API data.mos перестал работать и стал выдавать ошибку, дальнейшая работа шла с файлом, преобразованным в .csv формат и загруженным на диск компьютера.

In [12]:
schools_name_addresses_data_mos_wo_duplicate_2 = pd.read_csv('schools_name_addresses_data_mos_wo_duplicate.csv')
display(schools_name_addresses_data_mos_wo_duplicate_2)

,Unnamed: 0,ShortName,OrgType,FullName,WebSite,Email,PublicPhone,LicensingAndAccreditation,EducationalServices,NumberofStudentsInOO,...,LegalAddress,ChiefName,EducationPrograms,global_id,is_deleted,AdmArea,District,Address,ChiefPosition,Availability
0,0,ГБОУ ДО ДТДМ «Хорошево»,организация дополнительного образования,Государственное бюджетное образовательное учре...,dtim.mskobr.ru,"[{'is_deleted': 0, 'Email': 'horoshevo@edu.mos...","[{'is_deleted': 0, 'PublicPhone': '(499) 197-5...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"123154, ГОРОД МОСКВА, УЛИЦА МАРШАЛА ТУХАЧЕВСКО...",Ледовская Татьяна Леонидовна,Дополнительное образование | дополнительное об...,658727748,0,Северо-Западный административный округ,район Хорошёво-Мнёвники,"город Москва, улица Маршала Тухачевского, дом ...",директор,"[{'is_deleted': 0, 'global_id': 621246, 'avail..."
1,1,ГБУ «Лаборатория путешествий»,прочее,Государственное бюджетное учреждение города Мо...,lab-putesh.mskobr.ru,"[{'is_deleted': 0, 'Email': 'labp@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(495) 678-5...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"109052, ГОРОД МОСКВА, УЛИЦА НИЖЕГОРОДСКАЯ, ДОМ 3",Шпаро Матвей Дмитриевич,Профессиональное обучение # Дополнительное обр...,658727903,0,Центральный административный округ,Таганский район,"город Москва, Нижегородская улица, дом 3",директор,"[{'is_deleted': 0, 'global_id': 629752, 'avail..."
2,2,ГБПОУ колледж «Царицыно»,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,collegetsaritsyno.mskobr.ru,"[{'is_deleted': 0, 'Email': 'tsaritsino@edu.mo...","[{'is_deleted': 0, 'PublicPhone': '(495) 391-2...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1",Седова Наталья Николаевна,Профессиональное образование | среднее професс...,658727904,0,Южный административный округ,район Орехово-Борисово Северное,"город Москва, Шипиловский проезд, дом 37, корп...",директор,"[{'is_deleted': 0, 'global_id': 622223, 'avail..."
3,3,ГБПОУ колледж «Царицыно»,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,collegetsaritsyno.mskobr.ru,"[{'is_deleted': 0, 'Email': 'tsaritsino@edu.mo...","[{'is_deleted': 0, 'PublicPhone': '(495) 391-2...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1",Седова Наталья Николаевна,Профессиональное образование | среднее професс...,658727904,0,Южный административный округ,район Орехово-Борисово Северное,"город Москва, улица Генерала Белова, дом 6",директор,"[{'is_deleted': 0, 'global_id': 621152, 'avail..."
4,4,ГБПОУ колледж «Царицыно»,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,collegetsaritsyno.mskobr.ru,"[{'is_deleted': 0, 'Email': 'tsaritsino@edu.mo...","[{'is_deleted': 0, 'PublicPhone': '(495) 391-2...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1",Седова Наталья Николаевна,Профессиональное образование | среднее професс...,658727904,0,Южный административный округ,район Орехово-Борисово Северное,"город Москва, улица Генерала Белова, дом 4",директор,"[{'is_deleted': 0, 'global_id': 621135, 'avail..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4912,4912,ГБПОУ МГОК,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,mgok.mskobr.ru,"[{'is_deleted': 0, 'Email': 'mgok@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(495) 491-9...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2728, 'PupilsQ...",...,"125362, ГОРОД МОСКВА, УЛИЦА ВИШНЁВАЯ, ДОМ 5",Артемьев Игорь Анатольевич,Профессиональное обучение # Общее образование ...,1146537607,0,Северо-Западный административный округ,район Покровское-Стрешнево,"город Москва, Вишнёвая улица, дом 5",директор,"[{'is_deleted': 0, 'global_id': 696978, 'avail..."
4913,4913,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,район Хамовники,"город Москва, улица Тимура Фрунзе, дом 3, стро...",директор,"[{'is_deleted': 0, 'global_id': 696982, 'avail..."
4914,4914,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,район Хамовники,"город Москва, улица Тимура Фрунзе, дом 28",директор,"[{'is_deleted': 0, 'global_id': 696983, 'avail..."
4915,4915,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,район Хамовники,"город Москва, Пуговишников переулок, дом 7",директор,"[{'is_deleted': 0, 'global_id': 696972, 'avail..."
4916,4916,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,район Хамовники,"город Москва, Зубовский бульвар, дом 5, строен...",директор,"[{'is_deleted': 0, 'global_id': 696977, 'avail..."

Редактирование колонки ['District']

In [13]:
schools_addresses_new_district = schools_name_addresses_data_mos_wo_duplicate_2.copy()
schools_addresses_new_district['District'] = schools_addresses_new_district['District'].map(lambda x: str(x))
schools_addresses_new_district['District'] = schools_addresses_new_district['District'].str.replace('район ', '').str.replace(' район', '').str.replace('поселение ', '').str.replace('ё', 'е').str.replace('"', '')
display(schools_addresses_new_district)

,Unnamed: 0,ShortName,OrgType,FullName,WebSite,Email,PublicPhone,LicensingAndAccreditation,EducationalServices,NumberofStudentsInOO,...,LegalAddress,ChiefName,EducationPrograms,global_id,is_deleted,AdmArea,District,Address,ChiefPosition,Availability
0,0,ГБОУ ДО ДТДМ «Хорошево»,организация дополнительного образования,Государственное бюджетное образовательное учре...,dtim.mskobr.ru,"[{'is_deleted': 0, 'Email': 'horoshevo@edu.mos...","[{'is_deleted': 0, 'PublicPhone': '(499) 197-5...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"123154, ГОРОД МОСКВА, УЛИЦА МАРШАЛА ТУХАЧЕВСКО...",Ледовская Татьяна Леонидовна,Дополнительное образование | дополнительное об...,658727748,0,Северо-Западный административный округ,Хорошево-Мневники,"город Москва, улица Маршала Тухачевского, дом ...",директор,"[{'is_deleted': 0, 'global_id': 621246, 'avail..."
1,1,ГБУ «Лаборатория путешествий»,прочее,Государственное бюджетное учреждение города Мо...,lab-putesh.mskobr.ru,"[{'is_deleted': 0, 'Email': 'labp@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(495) 678-5...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"109052, ГОРОД МОСКВА, УЛИЦА НИЖЕГОРОДСКАЯ, ДОМ 3",Шпаро Матвей Дмитриевич,Профессиональное обучение # Дополнительное обр...,658727903,0,Центральный административный округ,Таганский,"город Москва, Нижегородская улица, дом 3",директор,"[{'is_deleted': 0, 'global_id': 629752, 'avail..."
2,2,ГБПОУ колледж «Царицыно»,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,collegetsaritsyno.mskobr.ru,"[{'is_deleted': 0, 'Email': 'tsaritsino@edu.mo...","[{'is_deleted': 0, 'PublicPhone': '(495) 391-2...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1",Седова Наталья Николаевна,Профессиональное образование | среднее професс...,658727904,0,Южный административный округ,Орехово-Борисово Северное,"город Москва, Шипиловский проезд, дом 37, корп...",директор,"[{'is_deleted': 0, 'global_id': 622223, 'avail..."
3,3,ГБПОУ колледж «Царицыно»,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,collegetsaritsyno.mskobr.ru,"[{'is_deleted': 0, 'Email': 'tsaritsino@edu.mo...","[{'is_deleted': 0, 'PublicPhone': '(495) 391-2...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1",Седова Наталья Николаевна,Профессиональное образование | среднее професс...,658727904,0,Южный административный округ,Орехово-Борисово Северное,"город Москва, улица Генерала Белова, дом 6",директор,"[{'is_deleted': 0, 'global_id': 621152, 'avail..."
4,4,ГБПОУ колледж «Царицыно»,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,collegetsaritsyno.mskobr.ru,"[{'is_deleted': 0, 'Email': 'tsaritsino@edu.mo...","[{'is_deleted': 0, 'PublicPhone': '(495) 391-2...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...",[],[],...,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1",Седова Наталья Николаевна,Профессиональное образование | среднее професс...,658727904,0,Южный административный округ,Орехово-Борисово Северное,"город Москва, улица Генерала Белова, дом 4",директор,"[{'is_deleted': 0, 'global_id': 621135, 'avail..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4912,4912,ГБПОУ МГОК,профессиональная образовательная организация,Государственное бюджетное профессиональное обр...,mgok.mskobr.ru,"[{'is_deleted': 0, 'Email': 'mgok@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(495) 491-9...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2728, 'PupilsQ...",...,"125362, ГОРОД МОСКВА, УЛИЦА ВИШНЁВАЯ, ДОМ 5",Артемьев Игорь Анатольевич,Профессиональное обучение # Общее образование ...,1146537607,0,Северо-Западный административный округ,Покровское-Стрешнево,"город Москва, Вишнёвая улица, дом 5",директор,"[{'is_deleted': 0, 'global_id': 696978, 'avail..."
4913,4913,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,Хамовники,"город Москва, улица Тимура Фрунзе, дом 3, стро...",директор,"[{'is_deleted': 0, 'global_id': 696982, 'avail..."
4914,4914,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,Хамовники,"город Москва, улица Тимура Фрунзе, дом 28",директор,"[{'is_deleted': 0, 'global_id': 696983, 'avail..."
4915,4915,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,Хамовники,"город Москва, Пуговишников переулок, дом 7",директор,"[{'is_deleted': 0, 'global_id': 696972, 'avail..."
4916,4916,ГБОУ школа № 1253,общеобразовательная организация,Государственное бюджетное общеобразовательное ...,sch1253c.mskobr.ru,"[{'is_deleted': 0, 'Email': '1253@edu.mos.ru',...","[{'is_deleted': 0, 'PublicPhone': '(499) 246-6...","[{'is_deleted': 0, 'LicenseAvailability': 'да'...","[{'is_deleted': 0, 'FullTimeEdu': 'да', 'PartT...","[{'is_deleted': 0, 'global_id': 2729, 'PupilsQ...",...,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...",Акулова Наталья Андреевна,Общее образование | дошкольное образование # О...,1146537608,0,Центральный административный округ,Хамовники,"город Москва, Зубовский бульвар, дом 5, строен...",директор,"[{'is_deleted': 0, 'global_id': 696977, 'avail..."

Создание датафрейма школ с адресами главных корпусов школ и их филиалов.

In [14]:
schools_addresses_new_district_with_address = schools_addresses_new_district[['ShortName', 'FullName', 'OrgType', 'global_id', 'AdmArea', 'District', 'LegalAddress' , 'Address']]
schools_addresses_new_district_with_address = schools_addresses_new_district_with_address.rename({'District' : 'home_adm_name'}, axis=1)
display(schools_addresses_new_district_with_address)

,ShortName,FullName,OrgType,global_id,AdmArea,home_adm_name,LegalAddress,Address
0,ГБОУ ДО ДТДМ «Хорошево»,Государственное бюджетное образовательное учре...,организация дополнительного образования,658727748,Северо-Западный административный округ,Хорошево-Мневники,"123154, ГОРОД МОСКВА, УЛИЦА МАРШАЛА ТУХАЧЕВСКО...","город Москва, улица Маршала Тухачевского, дом ..."
1,ГБУ «Лаборатория путешествий»,Государственное бюджетное учреждение города Мо...,прочее,658727903,Центральный административный округ,Таганский,"109052, ГОРОД МОСКВА, УЛИЦА НИЖЕГОРОДСКАЯ, ДОМ 3","город Москва, Нижегородская улица, дом 3"
2,ГБПОУ колледж «Царицыно»,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,658727904,Южный административный округ,Орехово-Борисово Северное,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1","город Москва, Шипиловский проезд, дом 37, корп..."
3,ГБПОУ колледж «Царицыно»,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,658727904,Южный административный округ,Орехово-Борисово Северное,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1","город Москва, улица Генерала Белова, дом 6"
4,ГБПОУ колледж «Царицыно»,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,658727904,Южный административный округ,Орехово-Борисово Северное,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1","город Москва, улица Генерала Белова, дом 4"
...,...,...,...,...,...,...,...,...
4912,ГБПОУ МГОК,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,1146537607,Северо-Западный административный округ,Покровское-Стрешнево,"125362, ГОРОД МОСКВА, УЛИЦА ВИШНЁВАЯ, ДОМ 5","город Москва, Вишнёвая улица, дом 5"
4913,ГБОУ школа № 1253,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537608,Центральный административный округ,Хамовники,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...","город Москва, улица Тимура Фрунзе, дом 3, стро..."
4914,ГБОУ школа № 1253,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537608,Центральный административный округ,Хамовники,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...","город Москва, улица Тимура Фрунзе, дом 28"
4915,ГБОУ школа № 1253,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537608,Центральный административный округ,Хамовники,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...","город Москва, Пуговишников переулок, дом 7"
4916,ГБОУ школа № 1253,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537608,Центральный административный округ,Хамовники,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...","город Москва, Зубовский бульвар, дом 5, строен..."

Создание датафрейма главных корпусов школ для дальнейшей их привязки к географическим координатам.

In [15]:
schools_addresses_new_district_with_address_geo = schools_addresses_new_district_with_address.drop_duplicates(subset='FullName')
schools_addresses_new_district_with_address_geo = schools_addresses_new_district_with_address_geo.reset_index()
display(schools_addresses_new_district_with_address_geo)

,index,ShortName,FullName,OrgType,global_id,AdmArea,home_adm_name,LegalAddress,Address
0,0,ГБОУ ДО ДТДМ «Хорошево»,Государственное бюджетное образовательное учре...,организация дополнительного образования,658727748,Северо-Западный административный округ,Хорошево-Мневники,"123154, ГОРОД МОСКВА, УЛИЦА МАРШАЛА ТУХАЧЕВСКО...","город Москва, улица Маршала Тухачевского, дом ..."
1,1,ГБУ «Лаборатория путешествий»,Государственное бюджетное учреждение города Мо...,прочее,658727903,Центральный административный округ,Таганский,"109052, ГОРОД МОСКВА, УЛИЦА НИЖЕГОРОДСКАЯ, ДОМ 3","город Москва, Нижегородская улица, дом 3"
2,2,ГБПОУ колледж «Царицыно»,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,658727904,Южный административный округ,Орехово-Борисово Северное,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1","город Москва, Шипиловский проезд, дом 37, корп..."
3,5,ГБОУДО «ДТДиМ «Преображенский»,Государственное бюджетное образовательное учре...,организация дополнительного образования,658727905,Восточный административный округ,Преображенское,"107553, ГОРОД МОСКВА, УЛИЦА ЧЕРКИЗОВСКАЯ Б., 15","город Москва, Большая Черкизовская улица, дом 15"
4,6,ГБПОУ ФК № 35,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,658727972,Южный административный округ,Бирюлево Восточное,"115404, ГОРОД МОСКВА, УЛИЦА ЛИПЕЦКАЯ, 2, 13","Российская Федерация, город Москва, внутригоро..."
...,...,...,...,...,...,...,...,...,...
585,4895,ГБОУ школа № 2094,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146138216,Новомосковский административный округ,Мосрентген,"108820, ГОРОД МОСКВА, ПОСЕЛЕНИЕ МОСРЕНТГЕН, ПО...","город Москва, поселение &quot;Мосрентген&quot;..."
586,4899,ГБОУ Цифровая школа,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146138217,Восточный административный округ,Преображенское,"111401, ГОРОД МОСКВА, УЛИЦА 3-Я ВЛАДИМИРСКАЯ, 26А","город Москва, Малая Семёновская улица, дом 15"
587,4900,ГБОУ школа № 1529 имени А.С. Грибоедова,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537606,Центральный административный округ,Хамовники,"119034, ГОРОД МОСКВА, ПЕРЕУЛОК 2-Й ОБЫДЕНСКИЙ, 9","город Москва, Староконюшенный переулок, дом 18"
588,4908,ГБПОУ МГОК,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,1146537607,Северо-Западный административный округ,Покровское-Стрешнево,"125362, ГОРОД МОСКВА, УЛИЦА ВИШНЁВАЯ, ДОМ 5","город Москва, Сходненский тупик, дом 1, строен..."
589,4913,ГБОУ школа № 1253,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537608,Центральный административный округ,Хамовники,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...","город Москва, улица Тимура Фрунзе, дом 3, стро..."

Соотношение адресов главных корпусов школ с их географическими координатами

In [16]:
schools_geo =  pd.read_excel('Образовательные учреждения города Москвы.xls')
schools_geo = pd.DataFrame(schools_geo)
geodata = schools_geo['geodata_center']
geodata_df = pd.DataFrame(geodata)
schools_geodata = pd.concat([schools_addresses_new_district_with_address_geo, geodata_df], axis=1)
display(schools_geodata)

,index,ShortName,FullName,OrgType,global_id,AdmArea,home_adm_name,LegalAddress,Address,geodata_center
0,0,ГБОУ ДО ДТДМ «Хорошево»,Государственное бюджетное образовательное учре...,организация дополнительного образования,658727748,Северо-Западный административный округ,Хорошево-Мневники,"123154, ГОРОД МОСКВА, УЛИЦА МАРШАЛА ТУХАЧЕВСКО...","город Москва, улица Маршала Тухачевского, дом ...","{""coordinates"":[37.4796073910091,55.7838269797..."
1,1,ГБУ «Лаборатория путешествий»,Государственное бюджетное учреждение города Мо...,прочее,658727903,Центральный административный округ,Таганский,"109052, ГОРОД МОСКВА, УЛИЦА НИЖЕГОРОДСКАЯ, ДОМ 3","город Москва, Нижегородская улица, дом 3","{""coordinates"":[37.6765457430991,55.7396604854..."
2,2,ГБПОУ колледж «Царицыно»,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,658727904,Южный административный округ,Орехово-Борисово Северное,"115569, ГОРОД МОСКВА, ПРОЕЗД ШИПИЛОВСКИЙ, 37, 1","город Москва, Шипиловский проезд, дом 37, корп...","{""coordinates"":[37.7158448802973,55.6218414311..."
3,5,ГБОУДО «ДТДиМ «Преображенский»,Государственное бюджетное образовательное учре...,организация дополнительного образования,658727905,Восточный административный округ,Преображенское,"107553, ГОРОД МОСКВА, УЛИЦА ЧЕРКИЗОВСКАЯ Б., 15","город Москва, Большая Черкизовская улица, дом 15","{""coordinates"":[37.7330417729531,55.8026265640..."
4,6,ГБПОУ ФК № 35,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,658727972,Южный административный округ,Бирюлево Восточное,"115404, ГОРОД МОСКВА, УЛИЦА ЛИПЕЦКАЯ, 2, 13","Российская Федерация, город Москва, внутригоро...","{""coordinates"":[37.6678226722998,55.6049547310..."
...,...,...,...,...,...,...,...,...,...,...
585,4895,ГБОУ школа № 2094,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146138216,Новомосковский административный округ,Мосрентген,"108820, ГОРОД МОСКВА, ПОСЕЛЕНИЕ МОСРЕНТГЕН, ПО...","город Москва, поселение &quot;Мосрентген&quot;...","{""coordinates"":[37.4319796639785,55.8295092891..."
586,4899,ГБОУ Цифровая школа,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146138217,Восточный административный округ,Преображенское,"111401, ГОРОД МОСКВА, УЛИЦА 3-Я ВЛАДИМИРСКАЯ, 26А","город Москва, Малая Семёновская улица, дом 15","{""coordinates"":[37.590880133857,55.73272967278..."
587,4900,ГБОУ школа № 1529 имени А.С. Грибоедова,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537606,Центральный административный округ,Хамовники,"119034, ГОРОД МОСКВА, ПЕРЕУЛОК 2-Й ОБЫДЕНСКИЙ, 9","город Москва, Староконюшенный переулок, дом 18","{""coordinates"":[37.6033129289185,55.7735173785..."
588,4908,ГБПОУ МГОК,Государственное бюджетное профессиональное обр...,профессиональная образовательная организация,1146537607,Северо-Западный административный округ,Покровское-Стрешнево,"125362, ГОРОД МОСКВА, УЛИЦА ВИШНЁВАЯ, ДОМ 5","город Москва, Сходненский тупик, дом 1, строен...","{""coordinates"":[37.7110491391208,55.7626930335..."
589,4913,ГБОУ школа № 1253,Государственное бюджетное общеобразовательное ...,общеобразовательная организация,1146537608,Центральный административный округ,Хамовники,"119021, ГОРОД МОСКВА, БУЛЬВАР ЗУБОВСКИЙ, ДОМ 5...","город Москва, улица Тимура Фрунзе, дом 3, стро...","{""coordinates"":[37.7792564298628,55.7560704490..."

Выгрузка с API data.mos информации о вводе учебно-воспитательных объектов

In [ ]:
'''key = '?api_key=<ваш ключ>'
url = 'https://apidata.mos.ru/v1/datasets/3264/rows' 


schools_objects_df = []

try:
    response = requests.get(url+key)
    json_response = response.json()

    schools_objects_df += json_response
except Exception as ex:
    print(ex)'''

Раскрытие информации об объектах.

In [ ]:
'''schools_objects_dataset = pd.DataFrame(schools_objects_df)
types = schools_objects_dataset["Cells"]

df_school_object = pd.DataFrame()
for i in range(len(types)):
    element = pd.DataFrame(types[i])
    df_school_object = pd.concat([df_school_object, element])
    i +=1
    
display(df_school_object)'''

In [ ]:
'''types2 = df_s["LaunchedFacilitiesIndicators"].apply(pd.Series)
plan_schools = pd.concat([df_school_object, types2], axis=1)
plan_schools = plan_schools.drop('LaunchedFacilitiesIndicators', 1)
display(plan_schools)'''

Так как сайт API data.mos перестал работать и стал выдавать ошибку, дальнейшая работа шла с файлом, преобразованным в .csv формат и загруженным на диск компьютера.

Группировка данных по году и типу учреждения, изменение типов колонок.

In [17]:
plan_schools_сsv = pd.read_csv('plan_schools.csv')
plan_schools_grouped = plan_schools_сsv.groupby(['ReportingYear', 'LaunchedEducationalFacilityType']).agg(sum).drop(['Unnamed: 0', 'global_id'], axis=1)
plan_schools_grouped['LaunchedFacilitiesPlannedQuantityYear'] = plan_schools_grouped['LaunchedFacilitiesPlannedQuantityYear'].astype(int)
plan_schools_grouped['LaunchedFacilitiesActualQuantityReportPeriod'] = plan_schools_grouped['LaunchedFacilitiesActualQuantityReportPeriod'].astype(int)
plan_schools_grouped['ActualVacanciesQuantityReportPeriod'] = plan_schools_grouped['ActualVacanciesQuantityReportPeriod'].astype(int)
plan_schools_grouped['PlannedVacanciesQuantityYear'] = plan_schools_grouped['PlannedVacanciesQuantityYear'].astype(int)
display(plan_schools_grouped)

                                                     LaunchedFacilitiesPlannedQuantityYear  \
ReportingYear LaunchedEducationalFacilityType
2017          Дошкольные образовательные учреждения                                    100
              Школы и блоки начальных классов                                           68
2018          Дошкольные образовательные учреждения                                     84
              Школы и блоки начальных классов                                           40
2019          Дошкольные образовательные учреждения                                    104
              Школы и блоки начальных классов                                          100
2020          Дошкольные образовательные учреждения                                     76
              Школы и блоки начальных классов                                          124
2021          Дошкольные образовательные учреждения                                     66
              Школы и блоки начальных классов                                           96

                                                     PlannedVacanciesQuantityYear  \
ReportingYear LaunchedEducationalFacilityType
2017          Дошкольные образовательные учреждения                         21980
              Школы и блоки начальных классов                               48012
2018          Дошкольные образовательные учреждения                         19660
              Школы и блоки начальных классов                               25716
2019          Дошкольные образовательные учреждения                         20176
              Школы и блоки начальных классов                                5480
2020          Дошкольные образовательные учреждения                         18700
              Школы и блоки начальных классов                               61900
2021          Дошкольные образовательные учреждения                         17226
              Школы и блоки начальных классов                               56700

                                                     LaunchedFacilitiesActualQuantityReportPeriod  \
ReportingYear LaunchedEducationalFacilityType
2017          Дошкольные образовательные учреждения                                            16
              Школы и блоки начальных классов                                                  12
2018          Дошкольные образовательные учреждения                                            38
              Школы и блоки начальных классов                                                  14
2019          Дошкольные образовательные учреждения                                            31
              Школы и блоки начальных классов                                                   8
2020          Дошкольные образовательные учреждения                                            27
              Школы и блоки начальных классов                                                  14
2021          Дошкольные образовательные учреждения                                            19
              Школы и блоки начальных классов                                                  20

                                                     ActualVacanciesQuantityReportPeriod
ReportingYear LaunchedEducationalFacilityType
2017          Дошкольные образовательные учреждения                                 2260
              Школы и блоки начальных классов                                       9578
2018          Дошкольные образовательные учреждения                                 9395
              Школы и блоки начальных классов                                      10216
2019          Дошкольные образовательные учреждения                                 5025
              Школы и блоки начальных классов                                       6925
2020          Дошкольные образовательные учреждения                                 5242
              Школы и блоки начальных классов                                       6495
2021          Дошкольные образовательные учреждения                                 3855
              Школы и блоки начальных классов                                      12325

Выявление недостроя количества мест.

In [18]:
plan_schools_grouped['ShortageFacilitiesQuanityYear'] = plan_schools_grouped['LaunchedFacilitiesPlannedQuantityYear'] - plan_schools_grouped['LaunchedFacilitiesActualQuantityReportPeriod']
plan_schools_grouped['ShortageVacanciesQuanityYear'] = plan_schools_grouped['PlannedVacanciesQuantityYear'] - plan_schools_grouped['ActualVacanciesQuantityReportPeriod']
plan_schools_grouped = plan_schools_grouped.reset_index()
display(plan_schools_grouped)

,ReportingYear,LaunchedEducationalFacilityType,LaunchedFacilitiesPlannedQuantityYear,PlannedVacanciesQuantityYear,LaunchedFacilitiesActualQuantityReportPeriod,ActualVacanciesQuantityReportPeriod,ShortageFacilitiesQuanityYear,ShortageVacanciesQuanityYear
0,2017,Дошкольные образовательные учреждения,100,21980,16,2260,84,19720
1,2017,Школы и блоки начальных классов,68,48012,12,9578,56,38434
2,2018,Дошкольные образовательные учреждения,84,19660,38,9395,46,10265
3,2018,Школы и блоки начальных классов,40,25716,14,10216,26,15500
4,2019,Дошкольные образовательные учреждения,104,20176,31,5025,73,15151
5,2019,Школы и блоки начальных классов,100,5480,8,6925,92,-1445
6,2020,Дошкольные образовательные учреждения,76,18700,27,5242,49,13458
7,2020,Школы и блоки начальных классов,124,61900,14,6495,110,55405
8,2021,Дошкольные образовательные учреждения,66,17226,19,3855,47,13371
9,2021,Школы и блоки начальных классов,96,56700,20,12325,76,44375

Расчет индекса недостроя мест.

In [19]:
def shortage_percent(planned, shortage):
    percent = round((shortage * 100) / planned, 2)
    print(percent)

shortage_vacancies_percent_year_preschool = shortage_percent(plan_schools_grouped[plan_schools_grouped['LaunchedEducationalFacilityType'] == 'Дошкольные образовательные учреждения']['PlannedVacanciesQuantityYear'].sum(), plan_schools_grouped[plan_schools_grouped['LaunchedEducationalFacilityType'] == 'Дошкольные образовательные учреждения']['ShortageFacilitiesQuanityYear'].sum())
shortage_vacancies_percent_year_school = shortage_percent(plan_schools_grouped[plan_schools_grouped['LaunchedEducationalFacilityType'] == 'Школы и блоки начальных классов']['PlannedVacanciesQuantityYear'].sum(), plan_schools_grouped[plan_schools_grouped['LaunchedEducationalFacilityType'] == 'Школы и блоки начальных классов']['ShortageFacilitiesQuanityYear'].sum())

0.31
0.18

Импорт, редактирование типов данных, изменение названий колонок и заполнение пропусков xls файлов с портала data.mos .

In [20]:
Перечень_негосударственных_образовательных_организаций_города_Москвы_реализующих_программ_дошкольного_образования = pd.read_excel('Перечень_негосударственных_образовательных_организаций_города_Москвы_реализующих_программ_дошкольного_образования_формат.xls')
Перечень_негосударственных_образовательных_организаций_города_Москвы_реализующих_программ_дошкольного_образования = Перечень_негосударственных_образовательных_организаций_города_Москвы_реализующих_программ_дошкольного_образования.drop(['KPP', 'Email', 'WebSite'], axis=1)

display(Перечень_негосударственных_образовательных_организаций_города_Москвы_реализующих_программ_дошкольного_образования)

,ID,FullName,ShortName,global_id,INN,OGRN,LegalForm,LegalAddress,NameOfLicensingAuthority,RegistrationLicenseNumber,LicenseIssueDate,Lic_blank_series,Lic_blank_number,Education_progs
0,1,Частное учреждение общеобразовательная организ...,ЧУОО «Европейская гимназия»,46554704,7701107636,1037739224808,Частное учреждение,"107014, г. Москва, ул. 3-я Сокольническая, дом 3",Департамент образования города Москвы,34382,28.11.2013,77Л01,0001803,дошкольное образование; начальное общее образо...
1,2,Частное общеобразовательное учреждение «Венда»,ЧОУ «Венда»,46554705,7702048454,1037739360416,Частное учреждение,"129075, город Москва, Прудовой проезд, дом 9, ...",Департамент образования города Москвы,37137,16.02.2016,77Л01,0007950,дошкольное образование; начальное общее образо...
2,3,Частное общеобразовательное учреждение - гимна...,Московская экономическая школа,46554706,7703093763,1027739153100,Частное учреждение,"123022, г. Москва, ул. Заморенова, д. 29",Департамент образования города Москвы,38322,05.04.2017,77Л01,0009158,дошкольное образование; начальное общее образо...
3,4,Общеобразовательное частное учреждение «Первая...,ОЧУ ПМГ,46554707,7703349609,1037739185472,Частное учреждение,"119002, город Москва, переулок Плотников, дом ...",Департамент образования города Москвы,39634,14.09.2018,77Л01,0010514,дошкольное образование; начальное общее образо...
4,5,Частное учреждение общеобразовательная организ...,ЧУОО «Солнечный ветер»,46554708,7704150213,1037739418914,Частное учреждение,"121019, г. Москва, Нащокинский пер., д. 12/15,...",Департамент образования города Москвы,36579,25.09.2015,77Л01,0007387,дошкольное образование; начальное общее образо...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,179,Некоммерческое партнерство Средняя общеобразов...,НП СОШ УЦ «ПЕРСПЕКТИВА»,1124004721,7736214244,1027739776833,Некоммерческое партнерство,"117208, г.Москва, вн.тер.г. муниципальный окру...",Департамент образования города Москвы,41403,29.04.2021,реестровая модель,реестровая модель,дошкольное образование; начальное общее образо...
145,180,Автономная Некоммерческая Организация Частная ...,АНО ЧДОО «Детская Билингвальная Академия»,1124004723,7751177043,1207700071952,Автономная некоммерческая организация,"108801, город Москва, пос. Сосенское, п. Комму...",Департамент образования города Москвы,41412,12.05.2021,реестровая модель,реестровая модель,дошкольное образование; дополнительное образов...
146,181,Автономная некоммерческая организация дошкольн...,АНО ДО «Растём Вместе»,1133390046,7733353970,1207700140955,Автономная некоммерческая организация,"125466, город Москва, улица Соколово-Мещерская...",Департамент образования города Москвы,41449,16.06.2021,реестровая модель,реестровая модель,дошкольное образование; дополнительное образов...
147,182,Негосударственное образовательное учреждение «...,НОУ «Православный Свято-Димитриевский детский ...,1139420489,7714100910,1027739753117,Негосударственное учреждение,"125315, Москва, ул. Самеда Вургуна, д. 3",Департамент образования города Москвы,22346,30.05.2007,А,250257,дошкольное образование; дополнительное образов...
148,183,Частное учреждение дошкольного образования «Це...,ЧУДО «Центр развития ребенка - детский сад с у...,1139420491,7728502263,1037789094760,Частное учреждение,"117574, город Москва, проспект Новоясеневский,...",Департамент образования города Москвы,40486,03.12.2019,77Л01,0011404,дошкольное образование; дополнительное образов...

In [21]:
Объекты_капитального_строительства =  pd.read_excel('Объекты капитального строительства.xls')
Объекты_капитального_строительства = Объекты_капитального_строительства.drop(['object_category_Id', 'Permission', 'EntryModifyReason', 'EntryDeleteReason', 'ParentEntries', 'ChildEntries', 'geoarea' ], axis=1)
Объекты_капитального_строительства = Объекты_капитального_строительства.drop('AreaCoordinates', axis=1)
Объекты_капитального_строительства['District'] = Объекты_капитального_строительства['District'].str.replace('район ', '').str.replace(' район', '').str.replace('поселение ', '').str.replace('ё', 'е').str.replace('"', '')
Объекты_капитального_строительства['CadastralNumber'] = Объекты_капитального_строительства['CadastralNumber'].fillna(0)
Объекты_капитального_строительства['GPZUDocumentNumber'] = Объекты_капитального_строительства['GPZUDocumentNumber'].fillna(0)
Объекты_капитального_строительства['GPZUDocumentStatus'] = Объекты_капитального_строительства['GPZUDocumentStatus'].fillna('нет информации')
Объекты_капитального_строительства['FunctionalForNG'] = Объекты_капитального_строительства['FunctionalForNG'].fillna('нет информации')
Объекты_капитального_строительства['DevelopmentArea'] = Объекты_капитального_строительства['DevelopmentArea'].fillna(0)
Объекты_капитального_строительства['FloorsAmount'] = Объекты_капитального_строительства['FloorsAmount'].fillna('нет информации')
display(Объекты_капитального_строительства)

,global_id,ID,ObjectName,AdmArea,District,ObjectAddress,Coordinates,ConsrtuctionWorkType,MainFunctional,SourceOfFinance,...,ObjectStatus,DeveloperInfo,CadastralNumber,GPZUDocumentNumber,GPZUDocumentDate,GPZUDocumentStatus,EntryState,EntryAddReason,FunctionalForNG,geodata_center
0,272726557,43,Дошкольное образовательное учреждение (2-я оче...,Северо-Восточный административный округ,Марьина Роща,"Москва, СВАО, Марьина роща, Новосущевская ул.,...","37.602203921205,55.788599041331",новое строительство,Дошкольная образовательная организация,внебюджетные источники,...,в строительстве,OrgForm:Открытое акционерное общество\nOrgName...,77:02:0024026:2081,RU77154000-038065,29.09.2011,действует,активна,новый объект,Дошкольная образовательная организация,"{""coordinates"":[37.602203921205,55.78859904133..."
1,272726564,771,"Телевизионный комплекс ОАО ""Телекомпания НТВ""",Северо-Восточный административный округ,Останкинский,"Москва, СВАО, район Останкинский, Новомосковск...","37.619060188133,55.817768093242",новое строительство,"Объект производства электронных компонентов, а...",внебюджетные источники,...,в строительстве,OrgForm:Акционерное общество\nOrgName:Телекомп...,77:02:0022005:1,RU77-174000-001921,08.09.2010,действует,активна,новый объект,Промышленно-производственный объект,"{""coordinates"":[37.619060188133,55.81776809324..."
2,272726691,738,Одноквартирные жилые дома (3-й пусковой комплекс),Северо-Западный административный округ,Куркино,"Москва, СЗАО, район Куркино, мкр. 1 АБВ, корп....","37.379301300613,55.906705621953",новое строительство,Малоэтажный многоквартирный дом,городской бюджет,...,в строительстве,OrgForm:Акционерное общество\nOrgName:УЭЗ\n\n,77:08:0001007:1,RU77-146000-005490,16.03.2012,аннулирован,активна,новый объект,Малоэтажный многоквартирный дом,"{""coordinates"":[37.379301300613,55.90670562195..."
3,272726733,1031,Реконструкция жилого дома,Юго-Западный административный округ,Южное Бутово,"Москва, ЮЗАО, район Южное Бутово, 1-я Павлогра...","37.575864205620,55.545354674543",реконструкция,Малоэтажный многоквартирный дом,внебюджетные источники,...,в строительстве,OrgForm:Физическое лицо\nOrgName:Хрящева Е С\n\n,77:06:0012015:1008,RU77-220000-006139,05.09.2012,действует,активна,новый объект,Малоэтажный многоквартирный дом,"{""coordinates"":[37.57586420562,55.545354674543..."
4,272726777,894,Индивидуальный монолитный 9-секционный 11-этаж...,Южный административный округ,Бирюлево Восточное,"Москва, ЮАО, район Бирюлево Восточное, 6-я Рад...","37.663362526202,55.606832113048",новое строительство,Многоэтажный многоквартирный дом,внебюджетные источники,...,в строительстве,OrgForm:Акционерное общество\nOrgName:Мосотдел...,77:05:0010002:4,RU77-111000-011832,20.04.2014,действует,активна,новый объект,Многоэтажный многоквартирный дом,"{""coordinates"":[37.663362526202,55.60683211304..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,1146493847,229703,Многофункциональный офисно-торговый центр по а...,Восточный административный округ,Метрогородок,"Москва, ВАО, Метрогородок, Тагильская ул. вл. 4","37.747559625889,55.818484822435",новое строительство,Офисное здание,внебюджетные источники,...,в строительстве,OrgForm:\nOrgName:Метромаш\n\n,0,0,NaN,нет информации,активна,новый объект,Офисное здание,"{""coordinates"":[37.747559625889,55.81848482243..."
1399,1146541162,196062,"""Жилой комплекс, 1 этап""",Южный административный округ,Даниловский,"Российская Федерация, город Москва, внутригоро...","37.645823674465,55.725728041479",новое строительство,Многоэтажный многоквартирный дом,внебюджетные источники,...,в строительстве,OrgForm:\nOrgName:СЗ Лайф Павелецкая\n\n,77:05:0001001:6411,0,NaN,нет информации,активна,новый объект,Многоэтажный многоквартирный дом,"{""coordinates"":[37.645823674465,55.72572804147..."
1400,1146958577,117260,Храмовый комплекс подворья Патриарха Московско...,Юго-Восточный административный округ,Люблино,"Москва, ВАО, Восточное Измайлово, Сиреневый бу...","37.818564318172,55.667225253849",новое строительство,Храм,внебюджетные источники,...,в строительстве,OrgForm:\nOrgName:Религиозная Организация Фина...,77:03:0005021:7366,RU77-121000-013167,11.06.2015,действует,активна,новый объект,Храм,"{""coordinates"":[37.818564318172,55.66722525384..."
1401,1146958630,182643,Физкультурно-оздоровительный комплекс. Реконст...,Северо-Западный административный округ,Митино,"Москва, СЗАО, Митино, Митинская ул. д. 24А стр. 1","37.372737540003,55.844163610714",реконструкция,Физкультурно-оздоровительный комплекс,внебюджетные источники,...,в строительстве,OrgForm:\nOrgName:Репаблика Новогорск\n\n,77:08:0002008:13793,0,NaN,нет информации,активна,новый объект,Физкультурно-оздоровительный комплекс,"{""coordinates"":[37.372737540003,55.84416361071..."
1402,1146971424,230521,Многофункциональный жилой комплекс с подземным...,Южный административный округ,Даниловский,"Российская Федерация, город Москва, внутригоро...","37.632418500677,55.706122069214",новое строительство,Многоэтажный многоквартирный дом,внебюджетные источники,...,в строительстве,OrgForm:\nOrgName:Нева Информ\n\n,77:05:0002002:117,0,NaN,нет информации,активна,новый объект,Многоэтажный многоквартирный дом,"{""coordinates"":[37.632418500677,55.70612206921..."

In [22]:
Участки_межевания_жилых_кварталов = pd.read_excel('Участки межевания жилых кварталов.xls')
Участки_межевания_жилых_кварталов = Участки_межевания_жилых_кварталов.drop('geoarea', axis=1)
display(Участки_межевания_жилых_кварталов)

,global_id,ID,ParcelName,ParcelClass,ParcelFunctionalUse,QuarterNumber,ParcelNumber,DevelopmentYear,ParcelArea,geodata_center
0,918869596,525941,Квартал 885/,Участки жилых зданий,территория участков жилой застройки,1,1,2004,11131.41,"{""coordinates"":[37.8038146720344,55.7962526725..."
1,918869598,604551,Участок 5/103/2008,Участки жилых зданий,Территория участков жилой застройки,103,5,2008,3674.39,"{""coordinates"":[37.1719073406809,55.9862305929..."
2,918869600,604547,Участок 1/102/2008,Участки жилых зданий,территории участков жилой застройки,102,1,2008,2060.28,"{""coordinates"":[37.6582272970391,55.7639729298..."
3,918869601,604540,Участок 2/102/2008,Участки жилых зданий,территории участков жилой застройки,102,2,2008,1329.72,"{""coordinates"":[37.6577123558795,55.7636453622..."
4,918869607,604550,Участок 10/103/2008,Участки жилых зданий,Территория участков жилой застройки,103,10,2008,8795.83,"{""coordinates"":[37.1772013627075,55.9858121771..."
...,...,...,...,...,...,...,...,...,...,...
43690,1136325840,1780478,Участок 11/31/2014,Участки общего пользования,"территории земельных участков, частей земельны...",31,11,2014,7680.00,"{""coordinates"":[37.4113042182846,55.6443128624..."
43691,1136325848,1780477,Участок 9/31/2014,Участки неустановленного назначения,"территории земельных участков, частей земельны...",31,9,2014,5240.28,"{""coordinates"":[37.4128034006298,55.6457288726..."
43692,1136325855,1780476,Участок 7/31/2014,Участки неустановленного назначения,"территории земельных участков, частей земельны...",31,7,2014,7858.58,"{""coordinates"":[37.4110058140389,55.6463906161..."
43693,1136325863,1780475,Участок 5/31/2014,"Участки нежилых зданий, сооружений","территории земельных участков, частей земельны...",31,5,2014,6817.18,"{""coordinates"":[37.408193705769,55.64716411732..."
43694,1136325891,1780474,Участок 3/31/2014,"Участки нежилых зданий, сооружений","территории земельных участков, частей земельны...",31,3,2014,9090.91,"{""coordinates"":[37.412949923146,55.64660791257..."

In [23]:
Адресный_реестр_объектов_недвижимости_города_Москвы = pd.read_excel('Адресный реестр объектов недвижимости города Москвы.xls')
Адресный_реестр_объектов_недвижимости_города_Москвы['P3'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P3'].str.replace('поселение ', '').str.replace('ё', 'е').str.replace('"', '')
Адресный_реестр_объектов_недвижимости_города_Москвы['P3'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P3'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P3' : 'Поселение'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P4'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P4'].str.replace('город ', '').str.replace('ё', 'е').str.replace('"', '')
Адресный_реестр_объектов_недвижимости_города_Москвы['P4'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P4'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P4' : 'Город'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P5'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P5'].str.replace('муниципальный округ ', '').str.replace('ё', 'е').str.replace('"', '')
Адресный_реестр_объектов_недвижимости_города_Москвы['P5'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P5'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P5' : 'Муниципальный округ (район)'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P1'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P1'].str.replace('город ', '').str.replace('ё', 'е').str.replace('"', '')
Адресный_реестр_объектов_недвижимости_города_Москвы['P1'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P1'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P1' : 'Город Москва'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P6'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P6'].str.replace('посёлок ', '').str.replace('деревня ', '').str.replace('село ', '').str.replace('ё', 'е').str.replace('"', '')
Адресный_реестр_объектов_недвижимости_города_Москвы['P6'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P6'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P6' : 'Населенный пункт'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P7'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P7'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P7' : 'Улица'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P90'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P90'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P90' : 'СНТ'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['L1_TYPE'] = Адресный_реестр_объектов_недвижимости_города_Москвы['L1_TYPE'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'L1_TYPE' : 'Тип недвижимости'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['L1_VALUE'] = Адресный_реестр_объектов_недвижимости_города_Москвы['L1_VALUE'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'L1_VALUE' : 'Нумерация типов недвижимости'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['L2_TYPE'] = Адресный_реестр_объектов_недвижимости_города_Москвы['L2_TYPE'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'L2_TYPE' : 'Корпус'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P0'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P0'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P0' : 'Страна'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['L2_VALUE'] = Адресный_реестр_объектов_недвижимости_города_Москвы['L2_VALUE'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'L2_VALUE' : 'Номер корпуса'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['L3_TYPE'] = Адресный_реестр_объектов_недвижимости_города_Москвы['L3_TYPE'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'L3_TYPE' : 'Строение'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['P2'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P2'].str.replace('ё', 'е').str.replace('"', '')
Адресный_реестр_объектов_недвижимости_города_Москвы['P2'] = Адресный_реестр_объектов_недвижимости_города_Москвы['P2'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'P2' : 'Внутригородская территория'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['L3_VALUE'] = Адресный_реестр_объектов_недвижимости_города_Москвы['L3_VALUE'].fillna(0)
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'L3_VALUE' : 'Нумерация строений'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['N_FIAS'] = Адресный_реестр_объектов_недвижимости_города_Москвы['N_FIAS'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'N_FIAS' : 'Уникальный номер ФИАС'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'D_FIAS' : 'Дата внесения в ФИАС'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['KAD_N'] = Адресный_реестр_объектов_недвижимости_города_Москвы['KAD_N'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'KAD_N' : 'Кадастровый номер недвижимости'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['Кадастровый номер недвижимости'] = Адресный_реестр_объектов_недвижимости_города_Москвы['Кадастровый номер недвижимости'].str.replace('KAD_N:', '').str.replace('\n\n', '')
Адресный_реестр_объектов_недвижимости_города_Москвы['KAD_ZU']= Адресный_реестр_объектов_недвижимости_города_Москвы['KAD_ZU'].fillna('нет информации')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.rename({'KAD_ZU' : 'Кадастровый номер земельного участка'}, axis=1)
Адресный_реестр_объектов_недвижимости_города_Москвы['Кадастровый номер земельного участка'] = Адресный_реестр_объектов_недвижимости_города_Москвы['Кадастровый номер земельного участка'].str.replace('KAD_ZU:', '').str.replace('\n\n', '')
Адресный_реестр_объектов_недвижимости_города_Москвы = Адресный_реестр_объектов_недвижимости_города_Москвы.drop(['object_category_Id', 'P91', 'L4_TYPE', 'L4_VALUE', 'L5_TYPE', 'L5_VALUE', 'geoarea'], axis=1)

display(Адресный_реестр_объектов_недвижимости_города_Москвы)

,OBJ_TYPE,OnTerritoryOfMoscow,ADDRESS,UNOM,Город Москва,Поселение,Город,Муниципальный округ (район),Населенный пункт,Улица,...,KLADR,TDOC,NDOC,DDOC,ADR_TYPE,VID,SOSTAD,STATUS,global_id,geodata_center
0,Здание,да,"Российская Федерация, город Москва, внутригоро...",2102436,Москва,нет информации,нет информации,Вешняки,нет информации,Косинская улица,...,77000000000040000,Распоряжение префектуры АО города Москвы,875-В-РП,28.07.2004,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,645622141,"{""coordinates"":[37.8281893944955,55.7174827851..."
1,Здание,да,"город Москва, Гороховский переулок, дом 21",5783,Москва,нет информации,нет информации,Басманный,нет информации,Гороховский переулок,...,77000000000112200,Распоряжение префектуры АО города Москвы,3026-р,04.07.2005,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,645622142,"{""coordinates"":[37.6680130722045,55.7662282721..."
2,Здание,да,"город Москва, Ленинградский проспект, дом 73А,...",2133081,Москва,нет информации,нет информации,Сокол,нет информации,Ленинградский проспект,...,77000000000168500,Распоряжение префектуры АО города Москвы,9169,31.10.2003,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,645622174,"{""coordinates"":[37.5134800723845,55.8035497986..."
3,Здание,да,"город Москва, улица Вострухина, дом 5А",2128644,Москва,нет информации,нет информации,Рязанский,нет информации,улица Вострухина,...,77000000000000300,Распоряжение префектуры АО города Москвы,3291,09.12.2003,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,645622205,"{""coordinates"":[37.797663793705,55.72004608615..."
4,Здание,да,"город Москва, улица Космонавта Волкова, дом 10...",3400130,Москва,нет информации,нет информации,Войковский,нет информации,улица Космонавта Волкова,...,77000000000100200,Распоряжение префектуры АО города Москвы,4227,06.08.2001,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,645622216,"{""coordinates"":[37.5148826460068,55.8153451882..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,Здание,да,"город Москва, улица Сущёвский Вал, дом 16, стр...",2308610,Москва,нет информации,нет информации,Марьина Роща,нет информации,улица Сущёвский Вал,...,77000000000060600,Распоряжение префектуры АО города Москвы,589,03.10.2011,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,647170603,"{""coordinates"":[37.6023295126311,55.7916826492..."
65531,Здание,да,"город Москва, Малый Власьевский переулок, дом ...",2101457,Москва,нет информации,нет информации,Хамовники,нет информации,Малый Власьевский переулок,...,77000000000704500,Распоряжение префектуры АО города Москвы,7552-р,26.11.2004,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,647170654,"{""coordinates"":[37.5939255571262,55.7468241757..."
65532,Здание,да,"Российская Федерация, город Москва, внутригоро...",4306784,Москва,нет информации,нет информации,Пресненский,нет информации,Пресненская набережная,...,77000000000738800,Распоряжение префектуры АО города Москвы,1736-р,08.05.2009,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,647170665,"{""coordinates"":[37.5367681623006,55.7467521845..."
65533,Здание,да,"город Москва, улица Новинки, дом 4",16395,Москва,нет информации,нет информации,Нагатинский Затон,нет информации,улица Новинки,...,77000000000201400,Распоряжение префектуры АО города Москвы,01-41-1806а,24.06.2005,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,647170676,"{""coordinates"":[37.6678018997562,55.6765554616..."
65534,Здание,да,"город Москва, Мурановская улица, дом 12Б",2111068,Москва,нет информации,нет информации,Бибирево,нет информации,Мурановская улица,...,77000000000191800,Распоряжение префектуры АО города Москвы,672,31.03.2005,Официальный,Адрес,Зарегистрирован в АР,Внесён в ГКН,647170687,"{""coordinates"":[37.6060352256904,55.8960725877..."

Создание датасетов с рандомными данными для демонстрации работы веб-сервиса на основе выданных датасетов.

In [24]:
Location_October = Location_July.copy()
random.seed(1)
Location_October['customers_cnt_home'] = [random.randint(Location_October['customers_cnt_home'].min(),Location_October['customers_cnt_home'].max()) for i in range(len(Location_October))]
Location_October['customers_cnt_job'] = [random.randint(Location_October['customers_cnt_job'].min(),Location_October['customers_cnt_job'].max()) for i in range(len(Location_October))]
Location_October['customers_cnt_day'] = [random.randint(Location_October['customers_cnt_day'].min(),Location_October['customers_cnt_day'].max()) for i in range(len(Location_October))]
Location_October['customers_cnt_move'] = [random.randint(Location_October['customers_cnt_move'].min(),Location_October['customers_cnt_move'].max()) for i in range(len(Location_October))]

Location_November = Location_July.copy()
random.seed(2)
Location_November['customers_cnt_home'] = [random.randint(Location_November['customers_cnt_home'].min(),Location_November['customers_cnt_home'].max()) for i in range(len(Location_November))]
Location_November['customers_cnt_job'] = [random.randint(Location_November['customers_cnt_job'].min(),Location_November['customers_cnt_job'].max()) for i in range(len(Location_November))]
Location_November['customers_cnt_day'] = [random.randint(Location_November['customers_cnt_day'].min(),Location_November['customers_cnt_day'].max()) for i in range(len(Location_November))]
Location_November['customers_cnt_move'] = [random.randint(Location_November['customers_cnt_move'].min(),Location_November['customers_cnt_move'].max()) for i in range(len(Location_November))]

Location_December = Location_July.copy()
random.seed(3)
Location_December['customers_cnt_home'] = [random.randint(Location_December['customers_cnt_home'].min(),Location_December['customers_cnt_home'].max()) for i in range(len(Location_December))]
Location_December['customers_cnt_job'] = [random.randint(Location_December['customers_cnt_job'].min(),Location_December['customers_cnt_job'].max()) for i in range(len(Location_December))]
Location_December['customers_cnt_day'] = [random.randint(Location_December['customers_cnt_day'].min(),Location_December['customers_cnt_day'].max()) for i in range(len(Location_December))]
Location_December['customers_cnt_move'] = [random.randint(Location_December['customers_cnt_move'].min(),Location_December['customers_cnt_move'].max()) for i in range(len(Location_December))]


display(Location_October, Location_November, Location_December)

,adm_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,1,41332,5586,99867,1855
1,2,155323,119961,92197,4362
2,3,22653,5027,92573,3954
3,4,72974,74925,33231,680
4,5,37021,66631,79710,4340
...,...,...,...,...,...
141,250,150558,71468,29832,4527
142,264,73033,88304,146035,2002
143,271,14618,158552,163642,4730
144,272,24578,133826,155147,1718
145,276,27929,68134,159598,2626

,adm_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,1,20934,82052,200916,7986
1,2,30118,118822,93793,3253
2,3,28358,145784,106928,1894
3,4,100759,159848,35280,627
4,5,50434,13209,69997,6948
...,...,...,...,...,...
141,250,35762,151040,169787,10097
142,264,81090,99094,6412,8581
143,271,94508,103914,85403,9863
144,272,134235,122642,125148,5597
145,276,14186,37823,140621,6891

,adm_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,1,68490,99912,145184,3282
1,2,161467,162638,128464,731
2,3,148776,155667,208451,5941
3,4,40299,166933,19457,2334
4,5,103091,36146,95603,764
...,...,...,...,...,...
141,250,9113,161686,27434,8374
142,264,114954,30987,151303,6751
143,271,158144,90694,29400,2401
144,272,88652,34085,176177,9265
145,276,11366,67395,101873,5570

In [25]:
CLocation_October = CLocation_July.copy()
random.seed(1)
CLocation_October['customers_cnt_home'] = [random.randint(CLocation_October['customers_cnt_home'].min(),CLocation_October['customers_cnt_home'].max()) for i in range(len(CLocation_October))]
CLocation_October['customers_cnt_job'] = [random.randint(CLocation_October['customers_cnt_job'].min(),CLocation_October['customers_cnt_job'].max()) for i in range(len(CLocation_October))]
CLocation_October['customers_cnt_day'] = [random.randint(CLocation_October['customers_cnt_day'].min(),CLocation_October['customers_cnt_day'].max()) for i in range(len(CLocation_October))]
CLocation_October['customers_cnt_move'] = [random.randint(CLocation_October['customers_cnt_move'].min(),CLocation_October['customers_cnt_move'].max()) for i in range(len(CLocation_October))]

CLocation_November = CLocation_July.copy()
random.seed(2)
CLocation_November['customers_cnt_home'] = [random.randint(CLocation_November['customers_cnt_home'].min(),CLocation_November['customers_cnt_home'].max()) for i in range(len(CLocation_November))]
CLocation_November['customers_cnt_job'] = [random.randint(CLocation_November['customers_cnt_job'].min(),CLocation_November['customers_cnt_job'].max()) for i in range(len(CLocation_November))]
CLocation_November['customers_cnt_day'] = [random.randint(CLocation_November['customers_cnt_day'].min(),CLocation_November['customers_cnt_day'].max()) for i in range(len(CLocation_November))]
CLocation_November['customers_cnt_move'] = [random.randint(CLocation_November['customers_cnt_move'].min(),CLocation_November['customers_cnt_move'].max()) for i in range(len(CLocation_November))]

CLocation_December = CLocation_July.copy()
random.seed(3)
CLocation_December['customers_cnt_home'] = [random.randint(CLocation_December['customers_cnt_home'].min(),CLocation_December['customers_cnt_home'].max()) for i in range(len(CLocation_December))]
CLocation_December['customers_cnt_job'] = [random.randint(CLocation_December['customers_cnt_job'].min(),CLocation_December['customers_cnt_job'].max()) for i in range(len(CLocation_December))]
CLocation_December['customers_cnt_day'] = [random.randint(CLocation_December['customers_cnt_day'].min(),CLocation_December['customers_cnt_day'].max()) for i in range(len(CLocation_December))]
CLocation_December['customers_cnt_move'] = [random.randint(CLocation_December['customers_cnt_move'].min(),CLocation_December['customers_cnt_move'].max()) for i in range(len(CLocation_December))]

display(CLocation_October, CLocation_November, CLocation_December)

,cell_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,32909,2202,14346,15056,192
1,32910,1034,10899,10936,248
2,33261,4180,13163,12480,430
3,33262,1932,13248,6635,140
4,33263,8118,2932,10191,285
...,...,...,...,...,...
10235,138913,4476,10253,1932,296
10236,138914,2262,4025,9359,254
10237,138915,7890,13923,3921,89
10238,138916,116,3283,11113,295
10239,139343,4944,6409,6564,341

,cell_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,32909,927,10525,15417,198
1,32910,1501,3954,13913,10
2,33261,1391,11093,8077,341
3,33262,5916,5143,4625,94
4,33263,2771,11561,2618,216
...,...,...,...,...,...
10235,138913,6199,172,9432,95
10236,138914,4365,5469,8418,267
10237,138915,6105,8200,12244,368
10238,138916,1552,9515,10081,97
10239,139343,6045,3077,10837,301

,cell_zid,customers_cnt_home,customers_cnt_job,customers_cnt_day,customers_cnt_move
0,32909,3899,10080,3989,307
1,32910,2137,4450,14512,431
2,33261,6062,11756,720,147
3,33262,7767,12846,2281,298
4,33263,1074,4282,5709,114
...,...,...,...,...,...
10235,138913,28,5947,9730,238
10236,138914,5504,7169,13011,137
10237,138915,7118,3197,9130,135
10238,138916,1037,12188,3073,146
10239,139343,7952,12581,5496,13

In [ ]:
CMatrix_Home_Work_October = CMatrix_Home_Work_July.copy()
random.seed(1)
CMatrix_Home_Work_October['customers_cnt'] = [random.randint(CMatrix_Home_Work_October['customers_cnt'].min(), CMatrix_Home_Work_October['customers_cnt'].max()) for i in range(len(CMatrix_Home_Work_October))]

CMatrix_Home_Work_November = CMatrix_Home_Work_July.copy()
random.seed(2)
CMatrix_Home_Work_November['customers_cnt'] = [random.randint(CMatrix_Home_Work_November['customers_cnt'].min(), CMatrix_Home_Work_November['customers_cnt'].max()) for i in range(len(CMatrix_Home_Work_November))]

CMatrix_Home_Work_December = CMatrix_Home_Work_July.copy()
random.seed(3)
CMatrix_Home_Work_December['customers_cnt'] = [random.randint(CMatrix_Home_Work_December['customers_cnt'].min(), CMatrix_Home_Work_December['customers_cnt'].max()) for i in range(len(CMatrix_Home_Work_December))]

#display(CMatrix_Home_Work_October, CMatrix_Home_Work_November, CMatrix_Home_Work_December)

In [26]:
Matrix_Home_Work_October = Matrix_Home_Work_July.copy()
random.seed(1)
Matrix_Home_Work_October['customers_cnt'] = [random.randint(Matrix_Home_Work_October['customers_cnt'].min(),Matrix_Home_Work_October['customers_cnt'].max()) for i in range(len(Matrix_Home_Work_October))]

Matrix_Home_Work_November = Matrix_Home_Work_July.copy()
random.seed(2)
Matrix_Home_Work_November['customers_cnt'] = [random.randint(Matrix_Home_Work_November['customers_cnt'].min(),Matrix_Home_Work_November['customers_cnt'].max()) for i in range(len(Matrix_Home_Work_November))]

Matrix_Home_Work_December = Matrix_Home_Work_July.copy()
random.seed(3)
Matrix_Home_Work_December['customers_cnt'] = [random.randint(Matrix_Home_Work_December['customers_cnt'].min(),Matrix_Home_Work_December['customers_cnt'].max()) for i in range(len(Matrix_Home_Work_December))]

display(Matrix_Home_Work_October, Matrix_Home_Work_November, Matrix_Home_Work_December)

       home_adm_zid  work_adm_zid  customers_cnt
0                -2             1          17611
1                -2             2          74606
2                -2             3         111074
3                -2             4         105154
4                -2             5         100109
...             ...           ...            ...
20603           276           250          35039
20604           276           264          45336
20605           276           271          99926
20606           276           272          65133
20607           276           276          88912

[20608 rows x 3 columns]

       home_adm_zid  work_adm_zid  customers_cnt
0                -2             1         113129
1                -2             2         111287
2                -2             3           7412
3                -2             4          12004
4                -2             5          11124
...             ...           ...            ...
20603           276           250          65070
20604           276           264          37448
20605           276           271         110929
20606           276           272          31458
20607           276           276          94094

[20608 rows x 3 columns]

       home_adm_zid  work_adm_zid  customers_cnt
0                -2             1          31190
1                -2             2          77678
2                -2             3          71333
3                -2             4          17094
4                -2             5          48490
...             ...           ...            ...
20603           276           250          99393
20604           276           264          65184
20605           276           271          15266
20606           276           272          63301
20607           276           276          93858

[20608 rows x 3 columns]